In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
path_2_root = '../'
path_2_data = path_2_root + 'data/csv/IEA/'
filename = 'Global Energy Review 2025 Dataset.xlsx'
full_filename = path_2_data + filename
sheet_name = 'World'
df = pd.read_excel(full_filename, sheet_name=sheet_name)
df.head(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Total energy supply (EJ),Unnamed: 10,Unnamed: 11,Unnamed: 12,Growth rate,Unnamed: 14
0,NaN,Publication,Category,Product,Flow,Unit,Region,NaN,NaN,2022,2023.0,2024.0,NaN,2022-23,2023-24
1,NaN,GER2025,Energy,Total,Total energy supply,PJ,World,NaN,Total,622,634.0,648.0,NaN,0.018,0.022
2,NaN,NaN,NaN,Renewables,NaN,NaN,NaN,NaN,Renewables,89,92.0,97.0,NaN,0.031,0.058
3,NaN,GER2025,Energy,Nuclear,Total energy supply,PJ,World,NaN,Nuclear,29,30.0,31.0,NaN,0.022,0.037
4,NaN,GER2025,Energy,Natural gas,Total energy supply,PJ,World,NaN,Natural gas,144,145.0,149.0,NaN,0.007,0.027
5,NaN,GER2025,Energy,Oil,Total energy supply,PJ,World,NaN,Oil,188,192.0,193.0,NaN,0.019,0.008
6,NaN,GER2025,Energy,Coal,Total energy supply,PJ,World,NaN,Coal,172,175.0,177.0,NaN,0.02,0.012
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electricity generation (TWh),NaN,NaN,NaN,Growth rate,NaN
9,NaN,Publication,Category,Product,Flow,Unit,Region,NaN,NaN,2022,2023.0,2024.0,NaN,2022-23,2023-24